config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :transport_modes, only: [:index, :show, :new, :create, :edit, :update] do
    resources :deadlines, only: [:create, :edit, :update]
    resources :weight_tables, only: [:create, :edit, :update]
    resources :distance_tables, only: [:create, :edit, :update]
    patch :activate, on: :member
    patch :deactivate, on: :member
  end
  resources :vehicles, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
    patch :activate, on: :member
    patch :deactivate, on: :member
  end

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_starts, only: [:new, :create, :destroy]
    resources :order_ends, only: [:new, :create]
    get 'search', on: :collection
    patch :order_confirmation, on: :member
    patch :set_canceled, on: :member

  end
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: { pending: 0, waiting_confirmation: 3, canceled: 5, on_route: 7, delivered: 10 }
  validates :takeout_address, :weight, :heigth, :width, :depth, :delivery_address, :name,
  :email, :customer_id, :total_distance, :status, presence: true
  validates :weight, :heigth, :width, :depth, comparison: { greater_than: 0 }
  validates :code, uniqueness: true
  validates :code, length: { is: 15 }
  validates :customer_id, length: { is: 14 }
  validates :customer_id, format: { with: /\d{14}/}

  before_validation :generate_code, on: :create
  has_one :order_start
  has_one :order_end

  private

  def generate_code
    self.code = SecureRandom.alphanumeric(15).upcase
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  skip_before_action :authenticate_user!, only: %i[show search]
  before_action :check_admin, only: %i[new create edit update set_pending set_canceled set_delivered]
  before_action :set_order,
                only: %i[show edit update set_pending set_canceled set_delivered order_confirmation]
  before_action :order_params, only: %i[create update]
  def index
    @orders = Order.all
  end

  def show
    @order_confirmation = OrderStart.find_by(order: @order)
  end

  def new
    @order = Order.new
  end

  def edit; end

  def create
    @order = Order.new(order_params)
    return redirect_to @order, notice: 'Ordem de Serviço cadastrada com sucesso.' if @order.save

    render :new
  end

  def update
    return redirect_to @order, notice: 'Ordem de Serviço atualizada com sucesso.' if @order.update(order_params)

    render :edit
  end

  def search
    @order_query = params['order_query']
    @order = Order.find_by(code: @order_query)
  end

  def order_confirmation
    @order.on_route!
    @order.order_start.vehicle.out_for_delivery!
    redirect_to @order, notice: 'Ordem de Serviço confirmada.'
  end

  def set_delivered
    @order.delivered!
    redirect_to @order, notice: 'Status da ordem de serviço atualizada.'
  end

  def set_canceled
    @order.canceled!
    @order.order_start.vehicle.available!
    redirect_to @order, notice: 'Status da ordem de serviço atualizada.'
  end

  private

  def order_params
    params.require(:order).permit(:takeout_address, :weight, :heigth, :width, :depth, :delivery_address, :name,
                                  :email, :customer_id, :total_distance, :status, :code)
  end

  def set_order
    @order = Order.find(params[:id])
  end
end

app/views/orders/_form.html.erb
<%= form_with model: @order do |order| %>

<% if @order.errors.any? %>

  <div class="bg-warning" id="error_explanation">

    <div>
      <% @order.errors.each do |error| %>
        <% flash.now[:alert] = error.full_message%>
        <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>

        <% end %>
   </div>
<% end %>
  </div>
<% end %>
<dl>
<h3>Informações de Retirada</h3>
<dt><%= order.label :takeout_address %></dt>
<dt><%= order.text_field :takeout_address %></dt>
<dt><%= order.label :weight %>(kg)</dt>
<dt><%= order.number_field :weight %></dt>
<dt><%= order.label :heigth %>(cm)</dt>
<dt><%= order.number_field :heigth %></dt>
<dt><%= order.label :width %>(cm)</dt>
<dt><%= order.number_field :width %></dt>
<dt><%= order.label :depth %>(cm)</dt>
<dt><%= order.number_field :depth %></dt>
<h3>Informações de Entrega</h3>
<dt><%= order.label :delivery_address %></dt>
<dt><%= order.text_field :delivery_address %></dt>
<dt><%= order.label :name %></dt>
<dt><%= order.text_field :name %></dt>
<dt><%= order.label :email %></dt>
<dt><%= order.text_field :email %></dt>
<dt><%= order.label :customer_id %></dt>
<dt><%= order.text_field :customer_id %></dt>
<br>
<dt><%= order.label :total_distance %>(km)</dt>
<dt><%= order.number_field :total_distance %></dt>
</dl>
<%= order.submit 'Enviar', class: "btn btn-primary  btn-m" %>

<% end %>

app/views/orders/edit.html.erb
<h1>Editar <%= "#{Order.model_name.human}: #{@order.code}" %></h1>
<%= render partial: 'form', locals: { order: @order }%>

app/views/orders/index.html.erb
<h1><%= Order.model_name.human(count: 2) %> Cadastradas</h1>
<%= link_to 'Cadastrar nova Ordem de Serviço', new_order_path, class: "btn btn-primary  btn-m" %>
<% if @orders.present? %>
<% @orders.each do |order| %>
<h3><%= Order.model_name.human %>: <%=link_to order.code, order %></h3>
<p><%= Order.human_attribute_name('status') %>: <%= t(order.status) %></p>
<%= %>
<% end %>
<% else %>
<h3>Nenhuma Ordem de serviço Cadastrada</h3>

<% end %>

app/views/orders/new.html.erb
<h1>Cadastrar nova <%= Order.model_name.human %></h1>
<%= render partial: 'form', locals: { order: @order }%>

app/views/orders/search.html.erb
<h1>Resultados da Busca por: <%= @order_query %></h1>
<% if @order.present? %>
<p><%= Order.model_name.human %> encontrada! </p>

<h3><%= link_to @order.code, @order %> </h3>
<p><%= Order.human_attribute_name('status') %>: <%= t(@order.status) %></p>

<% else %>
<h3>Nenhum resultado encontrado para a busca por: <%= @order_query %></h3>

<% end %>

app/views/orders/show.html.erb
<h1><%= "#{Order.model_name.human} #{@order.code}" %></h1>
<div tag="order-info">

<h3>Dados da Ordem de Serviço</h3>
<h6><%= Order.human_attribute_name('status') %>: <%= t(@order.status) %>
<% if @order.order_end.present? %>
<%= @order.order_end.reason.present? ? "(com atraso)" : "(no prazo)" %>
<% end %>
<p><%= Order.human_attribute_name('total_distance') %>: <%= @order.total_distance %>km</p>
</h6>
<div class="row">
    <div class="col-6">
    <dl>
        <div class="card bg-primary" style="width: 80%; padding: 2%; margin-bottom: 5%;">
            <h5 class="card-title">Informações do Fornecedor</h5>
            <dt><%= Order.human_attribute_name('takeout_address') %>: <%= @order.takeout_address %></dt>
            <dt>Peso: <%= @order.weight %>kg</dt>
            <dt>Dimensões: <%= "#{@order.heigth}x#{@order.width}x#{@order.depth}cm" %></dt>
        </div>
        <div class="card bg-primary" style="width: 80%; padding: 2%; margin-bottom: 5%;">
            <h5 class="card-title">Informações do Cliente</h5>
            <dt><%= Order.human_attribute_name('name') %>: <%= @order.name %></dt>
            <dt><%= Order.human_attribute_name('email') %>: <%= @order.email %></dt>
            <dt><%= Order.human_attribute_name('customer_id') %>: <%= @order.customer_id  %></dt>
            <dt><%= Order.human_attribute_name('delivery_address') %>: <%= @order.delivery_address %></dt>
        </div>
    </dl>
    </div>



    <div class="col-6">
        <% if @order.order_start.present? and !@order.canceled? %>
        <div class="card bg-primary" style="width: 80%; padding: 2%;">
            <h3 >Dados de Entrega</h3>
            <dl>
                <dt><%= "#{TransportMode.model_name.human}: #{@order.order_start.transport_mode.name}" %><dt>
                <dt><%= "#{Vehicle.model_name.human}: #{@order.order_start.vehicle.full_description}" %><dt>
                <dt><%= "#{OrderStart.human_attribute_name('shipping_fee')}: #{number_to_currency(@order.order_start.shipping_fee, locale: 'pt-BR')}" %></dt>
                <dt><%= "#{OrderStart.human_attribute_name('order_date')}: #{I18n.localize(@order.order_start.order_date)}" %></dt>
                <dt><%= "#{OrderStart.human_attribute_name('delivery_deadline')}: #{I18n.localize(@order.order_start.delivery_deadline)}" if @order.order_end.nil? %></dt>
            <dl>    
        <% end %>
        <% if @order.delivered? %>
            <dl>
                <dt>Pedido entregue em: <%= I18n.localize(@order.order_end.time) %></dt>
                <dt><%= "Motivo do Atraso: #{@order.order_end.reason}" if @order.order_end.reason.present? %></dt>
            </dl>
        </div>
        <% end %>        
    </div>
</div>

<div tag="pending-buttons">
<% if @order.pending? and current_user.present? %>
    <% if current_user.admin %>
        <p><%= link_to 'Editar Ordem de Serviço', edit_order_path(@order), {class: "btn btn-primary  btn-m"} %></p>
    <% end %>
    <p><%= link_to 'Iniciar Ordem de Serviço', new_order_order_start_path(@order), {class: "btn btn-primary  btn-m"} %></p>
<% end %>
</div>

<div tag="confirmation_buttons">
<% if @order.waiting_confirmation? and current_user.present? %>
    <p><%= button_to 'Confirmar Ordem de Serviço', order_confirmation_order_path, { method: 'patch', class: "btn btn-primary  btn-m"} %></p>
    <p><%= button_to 'Reconfigurar Ordem de Serviço', order_order_start_path(@order, @order.order_start), { method: 'delete', class: "btn btn-primary  btn-m"}%></p>
<% end %>
</div>

<div tag="on_route-buttons">
<% if @order.on_route? and current_user.present? %>
    <p><%= link_to 'Finalizar Ordem de Serviço', new_order_order_end_path(@order), {class: "btn btn-primary  btn-m"} %></p>
    <% if current_user.admin %>
        <p><%= button_to 'Marcar como Cancelada', set_canceled_order_path, { method: 'patch', class: "btn btn-primary  btn-m"} %></p>
    <% end %>
<% end %>
</div>
<div>
<p><%= link_to 'Voltar', orders_path, {class: "btn btn-primary  btn-m"} %></p>
</div>