config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :transport_modes, only: [:index, :show, :new, :create, :edit, :update] do
    resources :deadlines, only: [:create, :edit, :update]
    resources :weight_tables, only: [:create, :edit, :update]
    resources :distance_tables, only: [:create, :edit, :update]
    patch :activate, on: :member
    patch :deactivate, on: :member
  end
  resources :vehicles, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
    patch :activate, on: :member
    patch :deactivate, on: :member
  end

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_starts, only: [:new, :create, :destroy]
    resources :order_ends, only: [:new, :create]
    get 'search', on: :collection
    patch :order_confirmation, on: :member
    patch :set_canceled, on: :member

  end
end

app/models/transport_mode.rb
class TransportMode < ApplicationRecord
  enum status: { inactive: 0, active: 1 }

  has_many :weight_tables
  has_many :distance_tables
  has_many :deadlines
  has_many :vehicles
  has_many :order_starts

  validates :name, :min_weight, :max_weight, :min_distance, :max_distance, :fixed_rate, presence: true
  validates :min_weight, :min_distance, :max_weight, :max_distance, :fixed_rate, comparison: { greater_than: 0 }
  validates :max_weight, comparison: {greater_than: :min_weight}
  validates :max_distance, comparison: {greater_than: :min_distance}
  validate :no_tables, on: [:update]
  def with_weight_range
    "#{name} | #{min_weight}-#{max_weight}kg"
  end

  def with_distance_range
    "#{name} | #{min_distance}-#{max_distance}km"
  end

  def with_weight_and_distance_range
    "#{name} | #{min_weight}-#{max_weight}kg | #{min_distance}-#{max_distance}km"
  end

  def full_value(order)
    total_value = self.fixed_rate

    self.weight_tables.each do |range|
      if (range.min..range.max).include? order.weight
        total_value += (order.weight * range.value)
      end
    end

    self.distance_tables.each do |range|
      if (range.min..range.max).include? order.total_distance
        total_value += range.value
      end
    end
    total_value
  end

  def deadline(order)
    order_deadline = 0
    self.deadlines.each do |range|
      if (range.min..range.max).include? order.total_distance
        order_deadline += range.time
      end
    end
    order_deadline
  end

  def no_tables
    if self.weight_tables.empty? and self.active?
      errors.add(:status, ' não pode ser alterado para ativo com tabela de peso em branco')
    end
    if self.distance_tables.empty? and self.active?
      errors.add(:status, ' não pode ser alterado para ativo com tabela de distância em branco')
    end
    if self.deadlines.empty? and self.active?
      errors.add(:status, ' não pode ser alterado para ativo com tabela de prazos em branco')
    end
  end
end

app/controllers/transport_modes_controller.rb
class TransportModesController < ApplicationController
  before_action :check_admin, only: %i[new create edit update activate deactivate]
  before_action :set_transport_mode, only: %i[show edit update activate deactivate]
  before_action :transport_mode_params, only: %i[create update]

  def index
    @transport_modes = TransportMode.all
  end

  def show
    @transport_modes = TransportMode.all

    @weight_table = @transport_mode.weight_tables
    @weight_line = WeightTable.new

    @distance_table = @transport_mode.distance_tables
    @distance_line = DistanceTable.new

    @deadline = @transport_mode.deadlines
    @deadline_line = Deadline.new
  end

  def new
    @transport_mode = TransportMode.new
  end

  def edit; end

  def create
    @transport_mode = TransportMode.new(transport_mode_params)
    return redirect_to @transport_mode, notice: 'Modo de Transporte Cadastrado com sucesso.' if @transport_mode.save

    render :new
  end

  def update
    if @transport_mode.update(transport_mode_params)
      return redirect_to @transport_mode, notice: 'Modo de Transporte Atualizado com sucesso.'
    end

    render :edit
  end

  def activate
    @transport_mode.active!
    redirect_to @transport_mode, notice: 'Modo de Transporte ativado.'
  rescue StandardError
    redirect_to @transport_mode, alert: @transport_mode.errors.full_messages
  end

  def deactivate
    @transport_mode.inactive!
    redirect_to @transport_mode, notice: 'Modo de Transporte desativado.'
  end

  private

  def transport_mode_params
    params.require(:transport_mode).permit(:name, :min_distance,
                                           :max_distance, :min_weight, :max_weight, :fixed_rate)
  end

  def set_transport_mode
    @transport_mode = TransportMode.find(params[:id])
  end
end

app/views/transport_modes/_form.html.erb
<%= form_with model: @transport_mode do |trans| %>

<% if @transport_mode.errors.any? %>

  <div class="bg-warning" id="error_explanation">

    <div class="bg-info">
      <% @transport_mode.errors.each do |error| %>
        <% flash.now[:alert] = error.full_message%>
        <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>

        <% end %>
   </div>
<% end %>
  </div>
<% end %>
<div class="mb-3">
<dl>
<dt class="form-label"><%= trans.label :name %></dt>
<dt><%= trans.text_field :name %></dt>
<dt class="form-label"><%= trans.label :min_weight %>(kg)</dt>
<dt><%= trans.number_field :min_weight %></dt>
<dt class="form-label"><%= trans.label :max_weight %>(kg)</dt>
<dt><%= trans.number_field :max_weight %></dt>
<dt class="form-label"><%= trans.label :min_distance %>(km)</dt>
<dt><%= trans.number_field :min_distance %></dt>
<dt class="form-label"><%= trans.label :max_distance %>(km)</dt>
<dt><%= trans.number_field :max_distance %></dt>
<dt class="form-label"><%= trans.label :fixed_rate %></dt>
<dt><%= trans.number_field :fixed_rate %></dt>
</dl>
<%= trans.submit 'Enviar', class: "btn btn-primary  btn-m" %>
</div>
<% end %>

app/views/transport_modes/edit.html.erb
<h1>Editar <%= @transport_mode.name %></h1>
<%= render partial: 'form', locals: { order: @transport_mode }%>

app/views/transport_modes/index.html.erb
<h1><%= TransportMode.model_name.human(count: 2)%> disponíveis:</h1>
<%  if current_user.admin? %>
<p><%= link_to 'Cadastrar nova Modalidade de Transporte', new_transport_mode_path, class: "btn btn-primary  btn-m" %></p>
<% end %>

<% if @transport_modes.present? %>       
    <% @transport_modes.each_slice(3) do |trans| %>
        <div class="row">
        <% trans.each do |trans| %>
            <div class="col-4">
                <div class="card bg-primary" style="padding: 3%; width: 26rem; margin-bottom: 5%;">
                <h3 class="card-title"><%= "#{trans.name} (#{t(trans.status)})" %></h3>
                <p class="card-text btn btn-secondary"><%= link_to 'mais informações', trans%><p>
                </div>
            </div>
        <% end %>
        </div> 
    <% end %>    
<% else %>
    <h3>Nenhuma Modalidade de Transporte Cadastrada</h3>
<% end %>

app/views/transport_modes/new.html.erb
<h1>Cadastrar novo <%= TransportMode.model_name.human %></h1>
<%= render partial: 'form', locals: { order: @transport_mode }%>

app/views/transport_modes/show.html.erb
<article>
  <header>
    <h1><%= @transport_mode.name %> <%= @transport_mode.active? ? '(Ativo)' : '(Inativo)' %></h1>
    
    <div class="bg-warning" id="error_explanation">
      <% if !alert.nil? %>
        <% if !(alert.class == String) %>
          <% alert.each do |error| %>
            <p><%= error %></p>
    
        <% end %>
      <% end %>
    <% end %>
    </div>
  <header>
  <main>
    <p>
      <% if current_user.admin? %>
        <% if @transport_mode.active? %>
          <%= button_to 'Desativar', deactivate_transport_mode_url, { method: 'patch', class: "btn btn-primary  btn-m"} %>
        <% else %>
          <%= button_to 'Ativar', activate_transport_mode_url, { method: 'patch', class: "btn btn-primary  btn-m"} %>
        <% end %>
      <% end %>
    </p>
    
    <section>
      <h4>Tabela de informações de uso</h4>
      <table class="table bg-primary table-striped table-hover">
        <tr>
          <th scope="col"></th>
          <th scope="col">Carga Suportada</th>
          <th scope="col">Faixa de Distâncias</th>
        </tr>
        <tr>
          <td>Min</td>
          <td ><%= @transport_mode.min_weight %>kg</td>
          <td><%= @transport_mode.min_distance %>km</td>
        </tr>
        <tr>
          <td>Max</td>
          <td><%= @transport_mode.max_weight %>kg</td>
          <td><%= @transport_mode.max_distance %>km</td>
        </tr>
      </table>
      <p>
        <%= TransportMode.human_attribute_name('fixed_rate') %>: <%= number_to_currency(@transport_mode.fixed_rate, locale: 'pt-BR') %>
      </p>
      <div style='inline-block'>
        <% if current_user.admin? %>
          <p>
            <%= link_to 'Editar Modo de Transporte', edit_transport_mode_url, {class: "btn btn-primary  btn-m"} %>
          </p>
        <% end %>
      </div>
    </section>
    
    <section id="price_tables">
      <%= render partial: 'transport_modes/tables/table', locals: { 
                                                                    table_model: WeightTable,
                                                                    table: @weight_table, 
                                                                    table_url: 'weight_tables',
                                                                    line_type: @weight_line,
                                                                    trans_mod: @transport_mode,
                                                                    table_css: "weight-table",
                                                                    interval: 'Intervalo de pesos',
                                                                    unit: 'kg',
                                                                    price_for: 'Preço por kg'
                                                                  } %>
    
      <%= render partial: 'transport_modes/tables/table', locals: { 
                                                                    table_model: DistanceTable,
                                                                    table: @distance_table, 
                                                                    table_url: 'distance_tables',
                                                                    line_type: @distance_line,
                                                                    trans_mod: @transport_mode,
                                                                    table_css: "distance-table",
                                                                    interval: 'Intervalo de Distâncias',
                                                                    unit: 'km',
                                                                    price_for: 'Preço por faixa de km'
                                                                  } %>
    
      <%= render partial: 'transport_modes/tables/table', locals: { 
                                                                    table_model: Deadline,
                                                                    table: @deadline, 
                                                                    table_url: 'deadlines',
                                                                    line_type: @deadline_line,
                                                                    trans_mod: @transport_mode,
                                                                    table_css: "deadline-table",
                                                                    interval: 'Intervalo de Distâncias',
                                                                    unit: 'km',
                                                                    price_for: 'Tempo de Entrega'
                                                                  } %>
    </section>
  </main>
  <footer>
    <%= link_to 'Voltar', transport_modes_path, class: "btn bg-primary  btn-m" %>
  </footer>
</article>