config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :transport_modes, only: [:index, :show, :new, :create, :edit, :update] do
    resources :deadlines, only: [:create, :edit, :update]
    resources :weight_tables, only: [:create, :edit, :update]
    resources :distance_tables, only: [:create, :edit, :update]
    patch :activate, on: :member
    patch :deactivate, on: :member
  end
  resources :vehicles, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
    patch :activate, on: :member
    patch :deactivate, on: :member
  end

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_starts, only: [:new, :create, :destroy]
    resources :order_ends, only: [:new, :create]
    get 'search', on: :collection
    patch :order_confirmation, on: :member
    patch :set_canceled, on: :member

  end
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :transport_mode
  enum status: { maintenance: 0, available: 1, out_for_delivery: 5 }
  validates :nameplate, :vehicle_brand, :vehicle_model, :maximum_load, :manifacture_year, presence: true
  validates :maximum_load, :manifacture_year, comparison: { greater_than: 0 }
  validate :maximum_load_range
  has_one :order_start

  def full_description
    "#{vehicle_brand} #{vehicle_model} - #{nameplate}"
  end

  private

  def maximum_load_range
    if self.maximum_load.present? and self.transport_mode.present?
      if self.transport_mode.min_weight > self.maximum_load or self.transport_mode.max_weight < self.maximum_load
        errors.add(:maximum_load, "deve estar na faixa da Modalidade de Transporte.")
      end
    end
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :check_admin, only: %i[new create edit update activate deactivate]
  before_action :set_transport_mode, only: %i[new create edit update]
  before_action :set_vehicle, only: %i[show edit update activate deactivate]
  before_action :vehicle_params, only: %i[create update]
  def index
    @transport_modes = TransportMode.all
    @vehicles = Vehicle.all
  end

  def show; end

  def new
    @vehicle = Vehicle.new
  end

  def edit; end

  def create
    @vehicle = Vehicle.new(vehicle_params)
    return redirect_to @vehicle, notice: 'Veículo Cadastrado com sucesso.' if @vehicle.save

    render :new
  end

  def update
    return redirect_to @vehicle, notice: 'Veículo Atualizado com sucesso.' if @vehicle.update(vehicle_params)

    render :edit
  end

  def activate
    @vehicle.available!
    redirect_to @vehicle, notice: 'Veículo ativado para circulação.'
  end

  def deactivate
    @vehicle.maintenance!
    redirect_to @vehicle, notice: 'Veículo enviado para manutenção.'
  end

  def search
    @query = params['query']
    @vehicles = Vehicle.where('nameplate LIKE ?', "%#{@query}%")
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:nameplate, :vehicle_brand, :vehicle_model,
                                    :manifacture_year, :maximum_load, :transport_mode_id, :status)
  end

  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

  def set_transport_mode
    @transport_modes = TransportMode.all
  end
end

app/views/vehicles/_form.html.erb
<%= form_with model: @vehicle do |trans| %>

<% if @vehicle.errors.any? %>

  <div class="bg-warning" id="error_explanation">

    <div>
      <% @vehicle.errors.each do |error| %>
        <% flash.now[:alert] = error.full_message%>
        <% flash.each do |name, msg| %>
        <p><%= content_tag :div, msg, class: name %></p>

        <% end %>
   </div>
<% end %>
  </div>

<% end %>
<dl>
<dt><%= trans.label :vehicle_brand %></dt>
<dt><%= trans.text_field :vehicle_brand %></dt>
<dt><%= trans.label :vehicle_model %></dt>
<dt><%= trans.text_field :vehicle_model %></dt>
<dt><%= trans.label :nameplate %></dt>
<dt><%= trans.text_field :nameplate %></dt>
<dt><%= trans.label :manifacture_year %></dt>
<dt><%= trans.number_field :manifacture_year %></dt>
<dt><%= trans.label :maximum_load %>(kg)</dt>
<dt><%= trans.number_field :maximum_load %></dt>
<dt><%= trans.label :transport_mode_id %></dt>
<dt><%= trans.collection_select :transport_mode_id, @transport_modes, :id, :name, prompt:true %></dt>
</dl>
<%= trans.submit 'Enviar', class: "btn btn-primary  btn-m" %>

<% end %>

app/views/vehicles/edit.html.erb
<h1>Editar <%= @vehicle.full_description %></h1>
<%= render partial: 'form', locals: { order: @vehicle }%>

app/views/vehicles/index.html.erb
<h1><%= Vehicle.model_name.human(count: 2)%> disponíveis:</h1>
<div id="vehicle-search">
    <p>
        <%= form_with url: search_vehicles_path, method: :get do |form|%>
            <%= form.label :query, 'Buscar Veículo' %>
            <%= form.text_field :query %>
            <%= form.submit 'Buscar'%>
        <% end %>
    </p>
</div>

<div>
    <% if current_user.admin?%>
        <p><%= link_to 'Cadastrar novo Veículo', new_vehicle_path, class: "btn btn-primary  btn-m" %></p>
    <% end %>
</div>

<% if @vehicles.present? %>   
    <% @transport_modes.each_slice(3) do |trans| %>
        <div class="row">
        <% trans.each_with_index do |trans, index| %>
        <div class="col-4">
            <div id="accordion">
            <div class="card bg-primary">
                <div class="card-header" id="heading<%= index+1 %>">
                <h5 class="mb-0">
                    <button class="btn" data-toggle="collapse" data-target="#collapse<%= index+1 %>" aria-expanded="true" aria-controls="collapse<%= index+1 %>">
                        <%= trans.name %>
                    </button>
                </h5>
            </div>
                <div id="collapse<%= index+1 %>" class="collapse show" aria-labelledby="heading<%= index+1 %>" data-parent="#accordion">
                <div class="card-body">
                    <% @vehicles.where(transport_mode: trans).each do |vehicle| %>
                        <p><%= link_to vehicle.full_description, vehicle%> - <%= t(vehicle.status) %></p>
                    <% end %>
            </div>
                </div>
            </div>
        </div>   
        </div>
        <% end %>
        </div> 
    <% end %>    
<% else %>
    <h3>Nenhum <%= Vehicle.model_name.human %> disponível</h3>
<% end %>

app/views/vehicles/new.html.erb
<h1>Cadastrar <%= Vehicle.model_name.human %></h1>
<%= render partial: 'form', locals: { order: @vehicle }%>

app/views/vehicles/search.html.erb
<h1>Resultados da Busca por: <%= @query %></h1>
<% if @vehicles.present? %>
<p><%= @vehicles.count %> <%= Vehicle.model_name.human(count: @vehicles.count) %> <%= I18n.translate(:found, count: @vehicles.count) %></p>

<% @vehicles.each do |trans| %>
  <h3><%= link_to trans.full_description, trans %> <%= t(trans.status) %></h3>
<% end %>
<% else %>
<h2>Nenhum resultado encontrado para a busca por: <%= @query %></h2>

<% end %>

app/views/vehicles/show.html.erb
<h1><%= "#{@vehicle.full_description} (#{t(@vehicle.status)})" %></h1>
<h3>Informações do <%= Vehicle.model_name.human %></h3>
<dl>
<dt><%= Vehicle.human_attribute_name('vehicle_brand') %>: <%= @vehicle.vehicle_brand %></dt>
<dt><%= Vehicle.human_attribute_name('vehicle_model') %>: <%= @vehicle.vehicle_model %></dt>
<dt><%= Vehicle.human_attribute_name('nameplate') %>: <%= @vehicle.nameplate %></dt>
<dt><%= Vehicle.human_attribute_name('manifacture_year') %>: <%= @vehicle.manifacture_year %></dt>
<dt><%= Vehicle.human_attribute_name('maximum_load') %>: <%= @vehicle.maximum_load %>kg</dt>
<dt><%= Vehicle.human_attribute_name('transport_mode') %>: <%=link_to @vehicle.transport_mode.name, @vehicle.transport_mode %></dt>
</dl>

<div style='inline-block'>
<p><%= link_to 'Voltar', vehicles_path, {class: "btn btn-primary  btn-m"} %></p>
<% if current_user.admin and !@vehicle.out_for_delivery? %>
<p><%= link_to 'Editar dados do Veículo', edit_vehicle_path, {class: "btn btn-primary  btn-m"} %></p>
</div>
</p><%= button_to @vehicle.available? ? 'Mandar Veículo para manutenção' : 'Mandar Veículo para circulação', @vehicle.available? ? deactivate_vehicle_path : activate_vehicle_path, { method: 'patch', class: "btn btn-primary  btn-m"} %></p>
<% end %>