config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "home#index"
  resources :transport_modes, only: [:index, :show, :new, :create, :edit, :update] do
    resources :deadlines, only: [:create, :edit, :update]
    resources :weight_tables, only: [:create, :edit, :update]
    resources :distance_tables, only: [:create, :edit, :update]
    patch :activate, on: :member
    patch :deactivate, on: :member
  end
  resources :vehicles, only: [:index, :show, :new, :create, :edit, :update] do
    get 'search', on: :collection
    patch :activate, on: :member
    patch :deactivate, on: :member
  end

  resources :orders, only: [:index, :show, :new, :create, :edit, :update] do
    resources :order_starts, only: [:new, :create, :destroy]
    resources :order_ends, only: [:new, :create]
    get 'search', on: :collection
    patch :order_confirmation, on: :member
    patch :set_canceled, on: :member

  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShippingApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>
<nav id="nav links" class="border-bottom navbar navbar-expand-lg bg-primary p-3 rounded">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Transporte & Frete</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0" style="width: 55%;">
        <li class="nav-item" style="margin-right: 2%;">
          <a class="nav-link active bg-secondary rounded" aria-current="page" href=<%=transport_modes_path%>>Modos de Transporte</a>
        </li>
        <li class="nav-item" style="margin-right: 2%;">
          <a class="nav-link active bg-secondary rounded" aria-current="page" href=<%=vehicles_path%>>Veículos</a>
        </li>
        <li class="nav-item" style="margin-right: 2%;">
          <a class="nav-link active bg-secondary rounded" aria-current="page" href=<%=orders_path%>>Ordens de Serviço</a>
        </li>
      </ul>

      <div class="px-2">
      <%= form_with url: search_orders_url, method: :get do |form|%>
    <%= form.label :order_query, 'Consultar Ordem de Serviço' %>
    <%= form.text_field :order_query %>
    <%= form.submit 'Buscar', class: "btn btn-secondary  btn-m"%>
      <% end %>
      </div>
      <% if user_signed_in? %>
  Olá, <%= current_user.description %>
  <%= " 👑" if current_user.admin? %>
  <%= button_to 'Encerrar Sessão', destroy_user_session_path, method: 'delete', class: "btn btn-secondary btn-m" %>
  <% else %>
  <%= link_to 'Iniciar Sessão', new_user_session_path, class: "btn btn-secondary  btn-m" %>
  <% end %>
    </div>
  </div>
  </nav>
  <% if notice.present? %>
    <div class="bg-success rounded" style="margin: 1%;"><%= notice %></div>
  <% end %>
  <body class="bg-primary">
    
    <div class="container-flex bg-secondary mx-auto px-3 rounded"  style="padding: 2%; width: 98%;">
      <%= yield %>
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </div>
  </body>

</html>